main/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name="index"),
    path('edit/<int:id>', views.edit, name="edit"),
    path('add', views.add, name="add"),
    path('addSub/<int:id>', views.addSub, name="addSub"),
    path('editSub/<int:id>', views.editSub, name="editSub"),
    path('deleteSub/<int:id>', views.deleteSub, name="deleteSub"),
]

print/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('main.urls', 'index'), namespace='index')),
    path('print/', views.generate_and_print_pdf, name='print_receipt'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {{data.toko}}</title>
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
    <div class="w-100 ">
        <div class="display-5 mt-5 mb-3 text-center">Panel admin - {{data.toko}}</div>
        <div class="p-3 shadow rounded-3 d-flex justify-content-around">
            
            <form action="" method="post" class="col-6 shadow p-3" enctype="multipart/form-data">
                {% bootstrap_form form %}
                {% csrf_token %}
                <div class="d-flex justify-content-between">
                    <button type="submit" class="btn btn-primary">Simpan</button>
                    <div>
                        <a href="{% url 'print_receipt' %}" target="_blank" class="btn btn-danger">Test Print</a>
                    </div>
                </div>
            </form>
            {% if datas %}
            <div class="p-3 col-4 shadow">
                <table class="table">
                    <thead>
                      <tr>
                        <th scope="col">Urutan</th>
                        <th scope="col">Nama</th>
                        <th scope="col">Aksi</th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for row in datas %}
                        
                        <form action="{% url 'index:editSub' id=data.id %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="id" value="{{row.id}}">
                            <tr>
                                <td><input type="number" name="urutan" id="urutan" value="{{row.urutan}}" class="form-control"></td>
                                <td><input type="text" name="nama" id="nama" value="{{row.nama}}" class="form-control"></td>
                                <td class="d-flex gap-2">
                                    <button type="submit" name="action" value="edit" class="btn btn-primary btn-sm">Ubah</button>
                                    <button type="submit" name="action" value="delete" class="btn btn-danger btn-sm">Hapus</button>
                                </td>
                            </tr>
                        </form>
                        {% endfor %}
                        <form action="{% url 'index:addSub' id=data.id %}" method="post">
                            {% csrf_token %}
                            <tr>
                                <td><input type="number" name="urutan" id="urutan" class="form-control"></td>
                                <td><input type="text" name="nama" id="nama" class="form-control"></td>
                                <td><button type="submit" class="btn btn-primary btn-sm w-100">Tambah</button></td>
                            </tr>
                        </form>
                    </tbody>
                  </table>
                </div>
                {% endif %}
        </div>
    </div>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {{data.toko}}</title>
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
    <div class="container ">
       
        <div class="p-3 shadow rounded-3 mt-5 mb-3">
            
            <div class="d-flex justify-content-between my-4">
                <div class="h5   text-center">Panel admin</div>
                <a href="{% url 'index:add' %}" class="btn btn-primary self-center">Tambah</a>
              </div>
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Toko</th>
                    <th scope="col">Brand</th>
                    <th scope="col">Alamat</th>
                    <th scope="col">Ukuran</th>
                    <th scope="col">Edit</th>
                    <th scope="col">Utama</th>
                  </tr>
                </thead>
                <tbody>
                    {% for data in datas %}
                  <tr>
                    <th scope="row">1</th>
                    <td>{{data.toko}}</td>
                    <td>{{data.brand}}</td>
                    <td>{{data.alamat}}</td>
                    <td>{{data.page_width}} x {{data.page_higth}}</td>
                    <td class="d-flex gap-2"><a href="{% url 'index:edit' id=data.id %}" class="text-decoration-none">Edit</a><a href="{% url 'index:edit' id=data.id %}" class="text-decoration-none text-danger">Hapus</a></td>
                    <td>{% if data.utama %}Ya{% else %} <form action="" method="post">{% csrf_token %}<button type="submit" value="{{data.id}}" name="id" class="btn btn-sm btn-primary">Jadikan Utama</button></form> {% endif %}</td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
        </div>
    </div>
</body>
</html>

templates/subedit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {{data.toko}}</title>
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
    <div class="w-100 ">
        <div class="display-5 mt-5 mb-3 text-center">Edit</div>
        <div class="p-3 shadow rounded-3 ">
            <form action="" method="post" class="w-100" enctype="multipart/form-data">
                {% bootstrap_form form %}
                {% csrf_token %}
                <div class="d-flex justify-content-between">
                    <button type="submit" class="btn btn-primary">Simpan</button>
                    <div>
                        <a href="{% url 'print_receipt' %}" target="_blank" class="btn btn-danger">Test Print</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</body>
</html>